# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup MSbuild
      uses: microsoft/setup-msbuild@v1.0.1
   
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore NuGet Packages
      run: nuget restore TicHub.sln
    
    - name: Build the Solution
      run: msbuild TicHub.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: AzureDepBundle
        path: "./_build"
     
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Publish Artifacts to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: tickethub
        package: "./_build"
        slot-name: production
